export const LOGIN_TEXT = {
  brandAbbr:'WS',
  brandName:'WorkSync',
  brandTagline:'Workforce & Task Management',
  feature1:'Manage your team in one place',
  feature2:'Track tasks & attendance easily',
  feature3:'Real-time productivity dashboards',
  copyright:'© 2025 WorkSync. All rights reserved.',
  title:'Welcome back',
  subtitle:'Sign in to your WorkSync account',
  accountLabel:'Account',
  securityLabel:'Security',
  emailLabel:'Email Address',
  emailPlaceholder:'you@company.com',
  passwordLabel:'Password',
  passwordPlaceholder: '••••••••',
  forgotPassword:'Forgot password?',
  signIn:'Sign In',
  signingIn:'Signing in...',
  forgotTitle:'Forgot Password?',
  forgotSubtitle:'Enter your registered email and your IT team will help reset it.',
  submit:'Submit',
  cancel:'Cancel',
  toast:'🛠️ Please connect with your IT team to reset your password.',
  errorFillFields: 'Please fill in all fields.',
  errorInvalid:'Invalid email or password.',
};
export const LAYOUT_TEXT = {
  brand:'WorkSync',
  brandAbbr: 'WS',
  dashboard:'Dashboard',
  employees: 'Employees',
  attendance: 'Attendance',
  tasks:'Tasks',
  admin:'Admin',
  logout:'Logout',
  welcomePrefix:'Welcome, ',
};
export const DASHBOARD_TEXT = {
  title:'Dashboard',
  welcomePrefix:'Welcome back, ',
  roleLabel:'You are logged in as',
};

export const COMMON_TEXT = {
  actions:'Actions',
  save:'Save',
  cancel:'Cancel',
  loading:'Loading...',
  noRecords:'No records found',
  selectEmployee:'Select Employee',
  selectPlaceholder:'Select',
  refresh: 'Refresh',
};
export const ATTENDANCE_TEXT = {
  pageTitle:'Attendance',
  markCardTitle:'Mark Attendance',
  employeeLabel:'Employee',
  checkInBtn:'Check In',
  checkOutBtn:'Check Out',
  alreadyCheckedInMsg:'Already checked in today. You can check out below.',
  historyCardTitle:'Attendance History',
  filterByEmployeeLabel:'Filter by Employee',
  allEmployeesOption:'All Employees',
  columnEmployee:'Employee',
  columnCheckIn:'Check In',
  columnCheckOut:'Check Out',
  columnStatus:'Status',
  statusOptions:['Present', 'Late', 'Half Day', 'Absent'],
  checkInSuccess:'Attendance marked successfully',
  checkOutSuccess:'Checked out successfully',
  checkInError:'Failed to mark attendance',
  checkOutError:'Failed to check out',
  loadError:'Failed to load attendance records',
  selectEmployeeWarning:'Please select an employee first',
};
export const TASKS_TEXT = {
  pageTitle:'Tasks',
  createCardTitle:'Create Task',
  editCardTitle:'Edit Task',
  titleLabel:'Title',
  titlePlaceholder:'Enter task title',
  descriptionLabel:'Description',
  descriptionPlaceholder: 'Enter task description',
  priorityLabel:'Priority',
  priorityOptions:['Low', 'Medium', 'High'],
  dueDateLabel:'Due Date',
  createBtn:'Create Task',
  listCardTitle:'Task List',
  filterByStatusLabel:'Filter by Status',
  allStatusOption:'All Status',
  allPriorityOption:'All Priority',
  statusOptions:['Pending', 'In Progress', 'Completed'],
  columnTitle:'Title',
  columnPriority:'Priority',
  columnDueDate:'Due Date',
  columnStatus:'Status',
  columnAssignedTo:'Assigned To',
  editBtn:'Edit',
  deleteBtn:'Delete',
  updateBtn:'Update Task',
  cancelEditBtn:'Cancel',
  deleteConfirmMsg:'Are you sure you want to delete this task?',
  createSuccess:'Task created successfully',
  createError:'Failed to create task',
  updateSuccess:'Task updated successfully',
  updateError:'Failed to update task',
  deleteSuccess:'Task deleted successfully',
  deleteError:'Failed to delete task',
  loadError:'Failed to load tasks',
  validationMsg:'Please fill in all required fields',
};