export const COMMON_TEXT = {
  actions: 'Actions',
  save: 'Save',
  cancel: 'Cancel',
  loading: 'Loading...',
  noRecords: 'No records found',
  selectEmployee: 'Select Employee',
  selectPlaceholder: 'Select',
  refresh: 'Refresh'
};

export const ATTENDANCE_TEXT = {
  pageTitle: 'Attendance',
  markCardTitle: 'Mark Attendance',
  employeeLabel: 'Employee',
  checkInBtn: 'Check In',
  checkOutBtn: 'Check Out',
  alreadyCheckedInMsg: 'Already checked in today. You can check out below.',
  historyCardTitle: 'Attendance History',
  filterByEmployeeLabel: 'Filter by Employee',
  allEmployeesOption: 'All Employees',
  columnEmployee: 'Employee',
  columnCheckIn: 'Check In',
  columnCheckOut: 'Check Out',
  columnStatus: 'Status',
  statusOptions: ['Present', 'Late', 'Half Day', 'Absent'],
  checkInSuccess: 'Attendance marked successfully',
  checkOutSuccess: 'Checked out successfully',
  checkInError: 'Failed to mark attendance',
  checkOutError: 'Failed to check out',
  loadError: 'Failed to load attendance records',
  selectEmployeeWarning: 'Please select an employee first'
};

export const TASKS_TEXT = {
  pageTitle: 'Tasks',
  createCardTitle: 'Create Task',
  editCardTitle: 'Edit Task',
  titleLabel: 'Title',
  titlePlaceholder: 'Enter task title',
  descriptionLabel: 'Description',
  descriptionPlaceholder: 'Enter task description',
  priorityLabel: 'Priority',
  priorityOptions: ['Low', 'Medium', 'High'],
  dueDateLabel: 'Due Date',
  createBtn: 'Create Task',
  listCardTitle: 'Task List',
  filterByStatusLabel: 'Filter by Status',
  filterByPriorityLabel: 'Filter by Priority',
  allStatusOption: 'All Status',
  allPriorityOption: 'All Priority',
  statusOptions: ['Pending', 'In Progress', 'Completed'],
  columnTitle: 'Title',
  columnPriority: 'Priority',
  columnDueDate: 'Due Date',
  columnStatus: 'Status',
  columnAssignedTo: 'Assigned To',
  editBtn: 'Edit',
  deleteBtn: 'Delete',
  updateBtn: 'Update Task',
  cancelEditBtn: 'Cancel',
  deleteConfirmMsg: 'Are you sure you want to delete this task?',
  updateSuccess: 'Task updated successfully',
  updateError: 'Failed to update task',
  deleteSuccess: 'Task deleted successfully',
  deleteError: 'Failed to delete task',
  assignCardTitle: 'Assign Task',
  taskLabel: 'Task',
  employeeLabel: 'Employee',
  assignBtn: 'Assign',
  assignSuccess: 'Task assigned successfully',
  assignError: 'Failed to assign task',
  updateStatusLabel: 'Update Status',
  statusUpdateSuccess: 'Task status updated',
  statusUpdateError: 'Failed to update task status',
  commentsTitle: 'Comments',
  addCommentPlaceholder: 'Write a comment...',
  addCommentBtn: 'Add Comment',
  commentSuccess: 'Comment added successfully',
  commentError: 'Failed to add comment',
  createSuccess: 'Task created successfully',
  createError: 'Failed to create task',
  loadError: 'Failed to load tasks',
  validationMsg: 'Please fill in all required fields'
};