export const Constants = {
    title: 'Welcome back',
    subtitle: 'Sign in to your WorkSync account',
    accountLabel: 'Account',
    securityLabel: 'Security',
    emailLabel: 'Email Address',
    emailPlaceholder: 'you@company.com',
    passwordLabel: 'Password',
    passwordPlaceholder: '••••••••',
    forgotPassword: 'Forgot password?',
    signIn: 'Sign In',
    signingIn: 'Signing in...',
    forgotTitle: 'Forgot Password?',
    forgotSubtitle: 'Enter your registered email address and your IT team will help you reset it.',
    submit: 'Submit',
    cancel: 'Cancel',
    toast: '🛠️ Please connect with your IT team to reset your password.',
    brandname: 'WS',
};