export const constants = {
  APP_NAME: 'WorkSync',
  App_LOGO: 'WS',
  APP_TAGLINE: 'The all-in-one workforce management platform',
  EMPLOYEE_DEPARTMENT: '👥 Employee & Department Management',
  TASK_TRACKING_FEATURE: '✅ Task Tracking & Assignment',
  ATTENDANCE_REPORTING_FEATURE: '📊 Attendance & Reporting',
  LOGIN_EMAIL_ICON: '✉',
  LOGIN_PASSWORD_ICON: '🔒',
  LOGIN_ERROR_ICON: '⚠',
  COPYRIGHT: '© 2024 WorkSync. All rights reserved.',
  LOGIN_TITLE: 'Welcome back',
  LOGIN_SUBTITLE: 'Sign in to your WorkSync account',
  ACCOUNT_LABEL: 'Account',
  SECURITY_LABEL: 'Security',
  EMAIL_LABEL: 'Email address',
  EMAIL_PLACEHOLDER: 'Enter your Email',
  PASSWORD_LABEL: 'Password',
  PASSWORD_PLACEHOLDER: 'Enter your password',
  FORGOT_PASSWORD: 'Forgot password?',
  SIGN_IN: 'Sign In',
  LOADING: 'Signing in…',
  LOGIN_ERROR_FILL_FIELDS: 'Please enter your email and password.',
  LOGIN_ERROR_INVALID: 'Invalid email or password.',
  LOGIN_FORGOT_TITLE: 'Reset Password',
  LOGIN_FORGOT_SUBTITLE: 'Enter your email and we will send you reset instructions.',
  LOGIN_SUBMIT: 'Send Reset Link',
  LOGIN_CANCEL: 'Cancel',
  LOGIN_TOAST: '✅ Reset link sent! Check your inbox.',
  NAV_DASHBOARD: '📊 Dashboard',
  NAV_EMPLOYEES: '👥 Employees',
  NAV_ATTENDANCE: '🕐 Attendance',
  NAV_TASKS: '✅ Tasks',
  NAV_ADMIN: 'Admin',
  WELCOME_PREFIX: 'Hello, ',
  LOGOUT: '🚪 Logout',
  DASHBOARD_TITLE: 'Dashboard',
  DASHBOARD_WELCOME: 'Welcome to WorkSync',
  ADMIN_TITLE: 'Admin',
  ADMIN_SUBTITLE: 'System administration panel.',
  ATTENDANCE_TITLE: 'Attendance',
  ATTENDANCE_SUBTITLE: 'Attendance tracking coming soon.',
  TASKS_PAGE_TITLE: 'Task Management',
  TASKS_PAGE_SUBTITLE: 'Task management coming in a future sprint.',
  BACK_TO_EMPLOYEES: '← Back to Employees',
  EMPLOYEES_PAGE_TITLE: 'Employees',
  EMPLOYEES_PAGE_SUBTITLE: 'Manage your workforce from one place',
  ADD_EMPLOYEE: 'Add Employee',
  ADD_EMPLOYEE_TITLE: 'Add New Employee',
  EDIT_EMPLOYEE_TITLE: 'Edit Employee',
  UPDATE_EMPLOYEE: 'Update Employee',
  SAVE_BUTTON: 'Save',
  CANCEL_BUTTON: 'Cancel',
  RETRY_BUTTON: 'Retry',
  SEARCH_EMPLOYEES_PLACEHOLDER: 'Search employees',
  LOADING_EMPLOYEES: 'Loading employees...',
  LOADING_EMPLOYEE: 'Loading employee...',
  FULL_NAME_LABEL: 'Full Name',
  EMAIL_ADDRESS_LABEL: 'Email Address',
  PHONE_NUMBER_LABEL: 'Phone Number',
  DEPARTMENT_LABEL: 'Department',
  DEPARTMENT_PLACEHOLDER: 'Select a department',
  NAME_PLACEHOLDER: 'Enter your name',
  PHONE_PLACEHOLDER: '10-digit number',
  EMPLOYEE_FORM_SUBTITLE_ADD: 'Fill in the details to add a new employee.',
  EMPLOYEE_FORM_SUBTITLE_EDIT: 'Update the employee information below.',
  NAME_REQUIRED: 'Name is required.',
  NAME_MIN_LENGTH: 'Name must be at least 3 characters.',
  EMAIL_REQUIRED: 'Email is required.',
  EMAIL_INVALID: 'Enter a valid email address.',
  PHONE_INVALID: 'Enter a valid 10-digit phone number.',
  DEPARTMENT_REQUIRED: 'Please select a department.',
  SAVING_BUTTON: 'Saving...',
  UNABLE_TO_LOAD_EMPLOYEES: 'Unable to load employees. Please check your connection and try again.',
  LOAD_DEPARTMENTS_ERROR: 'Failed to load departments.',
  LOAD_EMPLOYEE_ERROR: 'Could not load that employee.',
  EMPLOYEE_ADDED_SUCCESS: 'Employee added successfully.',
  EMPLOYEE_UPDATED_SUCCESS: 'Employee updated successfully.',
  EMAIL_IN_USE_ERROR: 'That email is already in use.',
  GENERIC_ERROR: 'Something went wrong. Please try again.',
  DELETE_EMPLOYEE_TITLE: 'Delete Employee',
  DELETE_EMPLOYEE_MESSAGE_PREFIX: 'Are you sure you want to delete',
  DELETE_EMPLOYEE_MESSAGE_SUFFIX: 'This action cannot be undone.',
  DELETE_BUTTON: 'Delete',
  DELETE_SUCCESS: '{name} was deleted successfully.',
  DELETE_FAILED: 'Failed to delete employee. Please try again.',
  TABLE_NAME_HEADER: 'Name',
  TABLE_EMAIL_HEADER: 'Email',
  TABLE_DEPARTMENT_HEADER: 'Department',
  TABLE_PHONE_HEADER: 'Phone Number',
  TABLE_ACTIONS_HEADER: 'Actions',
  EMPLOYEE_PHONE_FALLBACK: '—',
  EDIT_EMPLOYEE_ACTION: 'Edit employee',
  DELETE_EMPLOYEE_ACTION: 'Delete employee',
  NO_EMPLOYEES_FOUND: 'No employees found',
  NO_EMPLOYEES_YET: 'No employees yet',
  NO_EMPLOYEES_SEARCH_SUBTITLE: 'Try a different search term.',
  NO_EMPLOYEES_EMPTY_SUBTITLE: 'Click Add Employee to get started.',
  EMPTY_STATE_TITLE: 'Nothing here yet',
  EMPTY_STATE_SUBTITLE: '',
  LOADING_MESSAGE: 'Loading...',
};
