export const constants = {
  APP_NAME: 'WorkSync',
  App_LOGO: 'WS',
  APP_TAGLINE: 'The all-in-one workforce management platform',
  EMPLOYEE_DEPARTMENT_FEATURE: '👥 Employee & Department Management',
  TASK_TRACKING_FEATURE: '✅ Task Tracking & Assignment',
  ATTENDANCE_REPORTING_FEATURE: '📊 Attendance & Reporting',
  LOGIN_EMAIL_ICON: '✉',
  LOGIN_PASSWORD_ICON: '🔒',
  LOGIN_ERROR_ICON: '⚠',
  COPYRIGHT: '© 2024 WorkSync. All rights reserved.',
  LOGIN_TITLE: 'Welcome',
  LOGIN_SUBTITLE: 'Sign in to your WorkSync account',
  EMAIL_LABEL: 'Email address',
  EMAIL_PLACEHOLDER: 'Enter your Email',
  PASSWORD_LABEL: 'Password',
  PASSWORD_PLACEHOLDER: 'Enter your password',
  FORGOT_PASSWORD: 'Forgot password?',
  SIGN_IN: 'Sign In',
  LOADING: 'Signing in…',
  LOGIN_ERROR_FILL_FIELDS: 'Please enter your email and password.',
  LOGIN_ERROR_INVALID: 'Invalid email or password.',
  LOGIN_FORGOT_TITLE: 'Reset Password',
  LOGIN_FORGOT_SUBTITLE: 'Enter your email and we will send you reset instructions.',
  LOGIN_SUBMIT: 'Send Reset Link',
  LOGIN_CANCEL: 'Cancel',
  LOGIN_TOAST: 'Please contact your IT team to reset your password.',
  NAV_DASHBOARD: '📊 Dashboard',
  NAV_EMPLOYEES: '👥 Employees',
  NAV_ATTENDANCE: '🕐 Attendance',
  NAV_TASKS: '✅ Tasks',
  NAV_ADMIN: 'Admin',
  WELCOME_PREFIX: 'Hello, ',
  LOGOUT: 'Logout',
  DASHBOARD_TITLE: 'Dashboard',
  DASHBOARD_WELCOME: 'Welcome to WorkSync',
  ADMIN_TITLE: 'Admin',
  ADMIN_SUBTITLE: 'System administration panel.',
  ATTENDANCE_TITLE: 'Attendance',
  ATTENDANCE_SUBTITLE: 'Attendance tracking coming soon.',
  TASKS_PAGE_TITLE: 'Task Management',
  TASKS_PAGE_SUBTITLE: 'View and manage all tasks across your team.',
  BACK_TO_EMPLOYEES: '← Back to Employees',
  EMPLOYEES_PAGE_TITLE: 'Employees',
  EMPLOYEES_PAGE_SUBTITLE: 'Manage your workforce from one place',
  ADD_EMPLOYEE: 'Add Employee',
  ADD_EMPLOYEE_TITLE: 'Add New Employee',
  EDIT_EMPLOYEE_TITLE: 'Edit Employee',
  UPDATE_EMPLOYEE: 'Update Employee',
  SAVE_BUTTON: 'Save',
  CANCEL_BUTTON: 'Cancel',
  RETRY_BUTTON: 'Retry',
  SEARCH_EMPLOYEES_PLACEHOLDER: 'Search employees',
  LOADING_EMPLOYEES: 'Loading employees...',
  LOADING_EMPLOYEE: 'Loading employee...',
  FULL_NAME_LABEL: 'Full Name',
  EMAIL_ADDRESS_LABEL: 'Email Address',
  PHONE_NUMBER_LABEL: 'Phone Number',
  DEPARTMENT_LABEL: 'Department',
  DEPARTMENT_PLACEHOLDER: 'Select a department',
  NAME_PLACEHOLDER: 'Enter your name',
  PHONE_PLACEHOLDER: '10-digit number',
  EMPLOYEE_FORM_SUBTITLE_ADD: 'Fill in the details to add a new employee.',
  EMPLOYEE_FORM_SUBTITLE_EDIT: 'Update the employee information below.',
  NAME_REQUIRED: 'Name is required.',
  NAME_MIN_LENGTH: 'Name must be at least 3 characters.',
  EMAIL_REQUIRED: 'Email is required.',
  EMAIL_INVALID: 'Enter a valid email address.',
  PHONE_INVALID: 'Enter a valid 10-digit phone number.',
  DEPARTMENT_REQUIRED: 'Please select a department.',
  SAVING_BUTTON: 'Saving...',
  UNABLE_TO_LOAD_EMPLOYEES: 'Unable to load employees. Please check your connection and try again.',
  LOAD_DEPARTMENTS_ERROR: 'Failed to load departments.',
  LOAD_EMPLOYEE_ERROR: 'Could not load that employee.',
  EMPLOYEE_ADDED_SUCCESS: 'Employee added successfully.',
  EMPLOYEE_UPDATED_SUCCESS: 'Employee updated successfully.',
  EMAIL_IN_USE_ERROR: 'That email is already in use.',
  GENERIC_ERROR: 'Something went wrong. Please try again.',
  DELETE_EMPLOYEE_TITLE: 'Delete Employee',
  DELETE_EMPLOYEE_MESSAGE_PREFIX: 'Are you sure you want to delete',
  DELETE_EMPLOYEE_MESSAGE_SUFFIX: 'This action cannot be undone.',
  DELETE_BUTTON: 'Delete',
  DELETE_SUCCESS: '{name} was deleted successfully.',
  DELETE_FAILED: 'Failed to delete employee. Please try again.',
  TABLE_NAME_HEADER: 'Name',
  TABLE_EMAIL_HEADER: 'Email',
  TABLE_DEPARTMENT_HEADER: 'Department',
  TABLE_PHONE_HEADER: 'Phone Number',
  TABLE_ACTIONS_HEADER: 'Actions',
  EMPLOYEE_PHONE_FALLBACK: '—',
  EDIT_EMPLOYEE_ACTION: 'Edit employee',
  DELETE_EMPLOYEE_ACTION: 'Delete employee',
  NO_EMPLOYEES_FOUND: 'No employees found',
  NO_EMPLOYEES_YET: 'No employees yet',
  NO_EMPLOYEES_SEARCH_SUBTITLE: 'Try a different search term.',
  NO_EMPLOYEES_EMPTY_SUBTITLE: 'Click Add Employee to get started.',
  ATTENDANCE_TODAY_STATUS: 'TODAY\'S STATUS',
  ATTENDANCE_NOT_CHECKED_IN: 'Not Checked In',
  ATTENDANCE_CHECKED_IN: 'Checked In',
  ATTENDANCE_PRESENT: 'Present',
  ATTENDANCE_CHECK_IN_BTN: 'Check In',
  ATTENDANCE_CHECK_OUT_BTN: 'Check Out',
  ATTENDANCE_CHECKING_IN: 'Checking in...',
  ATTENDANCE_CHECKING_OUT: 'Checking out...',
  ATTENDANCE_VIEW_HISTORY: 'View Full History →',
  ATTENDANCE_WORK_COMPLETE: '✅ Work complete for today!',
  ATTENDANCE_NO_EMPLOYEE: '⚠️ Your account is not linked to an employee profile.',
  ATTENDANCE_LOADING: 'Loading...',
  ATTENDANCE_CHECKED_IN_AT: 'Checked in at',
  ATTENDANCE_HISTORY_TITLE: 'Attendance History',
  ATTENDANCE_BACK: '← Back',
  ATTENDANCE_NO_RECORDS: 'No records found',
  ATTENDANCE_NO_RECORDS_SUB: 'Your attendance history will appear here once you start checking in.',
  ATTENDANCE_COL_DATE: 'Date',
  ATTENDANCE_COL_CHECK_IN: 'Check In',
  ATTENDANCE_COL_CHECK_OUT: 'Check Out',
  ATTENDANCE_COL_DURATION: 'Duration',
  ATTENDANCE_COL_STATUS: 'Status',
  ATTENDANCE_CHECK_IN_TIME_LABEL: 'CHECK IN TIME',
  ATTENDANCE_CHECK_OUT_TIME_LABEL: 'CHECK OUT TIME',
  ATTENDANCE_CLICK_TO_START: 'Click the button above to start your day.',
  ATTENDANCE_TODAY_TIMELINE: 'TODAY TIMELINE',
  ATTENDANCE_VIEW_HISTORY_TITLE: 'View full history',
  ATTENDANCE_VIEW_HISTORY_SUB: 'See your complete attendance records and check in/out history.',
  TASKS_ADD_BTN: 'Add Task',
  TASKS_LOADING: 'Loading tasks...',
  TASKS_LOAD_ERROR: 'Failed to load tasks. Please try again.',
  TASKS_EMPTY_TITLE: 'No tasks yet',
  TASKS_EMPTY_ADMIN_SUB: 'Click "Add Task" to create the first task.',
  TASKS_EMPTY_EMP_SUB: 'No tasks have been assigned to you yet.',
  TASKS_COL_TITLE: 'Title',
  TASKS_COL_PRIORITY: 'Priority',
  TASKS_COL_STATUS: 'Status',
  TASKS_COL_DUE: 'Due Date',
  TASKS_COL_ASSIGNED: 'Assigned To',
  TASK_FORM_ADD_TITLE: 'Add New Task',
  TASK_FORM_EDIT_TITLE: 'Edit Task',
  TASK_FORM_ADD_SUBTITLE: 'Fill in the details to create a task.',
  TASK_FORM_EDIT_SUBTITLE: 'Update the task information below.',
  TASK_TITLE_LABEL: 'Task Title',
  TASK_TITLE_PLACEHOLDER: 'Enter task title',
  TASK_DESC_LABEL: 'Description',
  TASK_DESC_PLACEHOLDER: 'Enter task description (optional)',
  TASK_PRIORITY_LABEL: 'Priority',
  TASK_STATUS_LABEL: 'Status',
  TASK_DUE_LABEL: 'Due Date',
  TASK_ASSIGN_LABEL: 'Assign Employees',
  TASK_ASSIGN_NONE: 'No employees found.',
  TASK_SAVING: 'Saving...',
  TASK_SAVE_BTN: 'Save Task',
  TASK_TITLE_REQUIRED: 'Task title is required.',
  TASK_SAVE_ERROR: 'Failed to save task. Please try again.',
  TASK_DETAIL_BACK: '← Back to Tasks',
  TASK_EDIT_BTN: 'Edit Task',
  TASK_DELETE_BTN: 'Delete Task',
  TASK_DELETE_CONFIRM: 'Are you sure you want to delete this task?',
  TASK_DETAIL_LOADING: 'Loading task...',
  TASK_DETAIL_NOT_FOUND: 'Task not found.',
  TASK_ASSIGNED_TO: 'Assigned To',
  TASK_CREATED_BY: 'Created By',
  TASK_CREATED_AT: 'Created',
  TASK_NO_ASSIGNEES: 'No employees assigned.',
  TASK_UPDATE_STATUS_LABEL: 'Update Status',
  TASK_STATUS_UPDATING: 'Updating...',
  TASK_STATUS_UPDATE_BTN: 'Update Status',
  TASK_STATUS_UPDATED_OK: 'Status updated successfully.',
  TASK_STATUS_UPDATE_ERROR: 'Failed to update status.',
  TASK_COMMENTS_TITLE: 'Comments',
  TASK_NO_COMMENTS: 'No comments yet.',
  TASK_COMMENT_PLACEHOLDER: 'Write a comment...',
  TASK_COMMENT_BTN: 'Add Comment',
  TASK_COMMENT_ADDING: 'Adding...',
  TASK_COMMENT_ERROR: 'Failed to add comment.',
  TASK_SELECT_EMPLOYEE_PLACEHOLDER: 'Select employee…',
  TASK_ASSIGN_BTN: 'Assign',
  TASK_COMMENT_POST_BTN: 'Post',
  TASK_COMMENT_POSTING: 'Posting…',
  TASK_META_CREATED_BY: 'Created by',
  TASK_META_DUE: 'Due',
  DASHBOARD_SUBTITLE: 'Here\'s what\'s happening across your team today.',
  DASHBOARD_LOADING: 'Loading dashboard...',
  DASHBOARD_ERROR: 'Failed to load dashboard data. Please try again.',
  DASHBOARD_RETRY:'Retry',
  DASHBOARD_TOTAL_TASKS: 'Total Tasks',
  DASHBOARD_COMPLETED_TASKS:'Completed',
  DASHBOARD_PENDING_TASKS:'Pending',
  DASHBOARD_ATTENDANCE: 'Attendance Today',
  DASHBOARD_ATTENDANCE_SUFFIX:    '%',
  DASHBOARD_TASKS_CHART_TITLE:'Task Status Overview',
  DASHBOARD_WORKLOAD_CHART_TITLE: 'Employee Workload',
  DASHBOARD_EMPLOYEE_COL: 'Employee',
  DASHBOARD_TASKS_COL: 'Tasks',
  DASHBOARD_NO_WORKLOAD: 'No workload data available.',
  NOTIF_TITLE:'Notifications',
  NOTIF_MARK_ALL_READ:'Mark all as read',
  NOTIF_EMPTY: 'You\'re all caught up!',
  NOTIF_BADGE_ARIA: 'unread notifications',
  NOTIF_MARK_READ_ERROR:'Failed to mark as read.',
  NOTIF_MARK_ALL_ERROR:  'Failed to mark all as read.',
  EMPTY_STATE_TITLE: 'Nothing here yet',
  EMPTY_STATE_SUBTITLE: '',
  LOADING_MESSAGE: 'Loading...',
  TASK_UPDATED_OK: 'Task updated successfully.',
  TASK_UPDATE_FAILED: 'Failed to update task.',
  TASK_ASSIGN_SUCCESS_SUFFIX: ' assigned',
  TASK_ASSIGN_FAILED: 'Failed to assign.',
  TASK_COMMENT_ADDED: 'Comment added.',
  TASK_COMMENT_FAILED: 'Failed to add comment.',
  TASK_UNASSIGN_SUFFIX: ' removed',
  TASK_UNASSIGN_FAILED: 'Failed to remove.',
  TASK_DELETED_OK: 'Task deleted.',
  TASK_DELETE_FAILED_DETAIL: 'Failed to delete.',
  TASK_NOT_LINKED: 'Your account is not linked to an employee profile. Please contact your Admin.',
  FAILED_TO_LOAD : 'Failed to load preview',
  LOGOUT_TOAST: 'You have been logged out successfully.'
};
