export const APP_CONSTANTS = {
  APP_NAME: 'WorkSync',
  BACK_TO_EMPLOYEES: '← Back to Employees',
  EMPLOYEES_PAGE_TITLE: 'Employees',
  EMPLOYEES_PAGE_SUBTITLE: 'Manage your workforce from one place',
  ADD_EMPLOYEE: 'Add Employee',
  ADD_EMPLOYEE_TITLE: 'Add New Employee',
  EDIT_EMPLOYEE_TITLE: 'Edit Employee',
  UPDATE_EMPLOYEE: 'Update Employee',
  SAVE_BUTTON: 'Save',
  CANCEL_BUTTON: 'Cancel',
  RETRY_BUTTON: 'Retry',
  SEARCH_EMPLOYEES_PLACEHOLDER: 'Search employees',
  LOADING_EMPLOYEES: 'Loading employees...',
  LOADING_EMPLOYEE: 'Loading employee...',
  FULL_NAME_LABEL: 'Full Name',
  EMAIL_ADDRESS_LABEL: 'Email Address',
  PHONE_NUMBER_LABEL: 'Phone Number',
  DEPARTMENT_LABEL: 'Department',
  DEPARTMENT_PLACEHOLDER: 'Select a department',
  NAME_PLACEHOLDER: 'Enter your name',
  EMAIL_PLACEHOLDER: 'Enter your Email',
  PHONE_PLACEHOLDER: '10-digit number',
  EMPLOYEE_FORM_SUBTITLE_ADD: 'Fill in the details to add a new employee.',
  EMPLOYEE_FORM_SUBTITLE_EDIT: 'Update the employee information below.',
  NAME_REQUIRED: 'Name is required.',
  NAME_MIN_LENGTH: 'Name must be at least 3 characters.',
  EMAIL_REQUIRED: 'Email is required.',
  EMAIL_INVALID: 'Enter a valid email address.',
  PHONE_INVALID: 'Enter a valid 10-digit phone number.',
  DEPARTMENT_REQUIRED: 'Please select a department.',
  SAVING_BUTTON: 'Saving...',
  UNABLE_TO_LOAD_EMPLOYEES: 'Unable to load employees. Please check your connection and try again.',
  LOAD_DEPARTMENTS_ERROR: 'Failed to load departments.',
  LOAD_EMPLOYEE_ERROR: 'Could not load that employee.',
  EMPLOYEE_ADDED_SUCCESS: 'Employee added successfully.',
  EMPLOYEE_UPDATED_SUCCESS: 'Employee updated successfully.',
  EMAIL_IN_USE_ERROR: 'That email is already in use.',
  GENERIC_ERROR: 'Something went wrong. Please try again.',
  DELETE_EMPLOYEE_TITLE: 'Delete Employee',
  DELETE_EMPLOYEE_MESSAGE_PREFIX: 'Are you sure you want to delete',
  DELETE_EMPLOYEE_MESSAGE_SUFFIX: 'This action cannot be undone.',
  DELETE_BUTTON: 'Delete',
  DELETE_SUCCESS: '{name} was deleted successfully.',
  DELETE_FAILED: 'Failed to delete employee. Please try again.',
  TABLE_NAME_HEADER: 'Name',
  TABLE_EMAIL_HEADER: 'Email',
  TABLE_DEPARTMENT_HEADER: 'Department',
  TABLE_PHONE_HEADER: 'Phone Number',
  TABLE_ACTIONS_HEADER: 'Actions',
  EMPLOYEE_PHONE_FALLBACK: '—',
  EDIT_EMPLOYEE_ACTION: 'Edit employee',
  DELETE_EMPLOYEE_ACTION: 'Delete employee',
  NO_EMPLOYEES_FOUND: 'No employees found',
  NO_EMPLOYEES_YET: 'No employees yet',
  NO_EMPLOYEES_SEARCH_SUBTITLE: 'Try a different search term.',
  NO_EMPLOYEES_EMPTY_SUBTITLE: 'Click Add Employee to get started.'
};
export const LOGIN_TEXT = {
  brandAbbr: 'WS',
  brandName: 'WorkSync',
  brandTagline: 'The all-in-one workforce management platform',
  feature1: 'Employee & Department Management',
  feature2: 'Task Tracking & Assignment',
  feature3: 'Attendance & Reporting',
  copyright: '© 2024 WorkSync. All rights reserved.',
  title: 'Welcome back',
  subtitle: 'Sign in to your WorkSync account',
  accountLabel: 'Account',
  securityLabel: 'Security',
  emailLabel: 'Email address',
  emailPlaceholder: 'Enter your Email',
  passwordLabel: 'Password',
  passwordPlaceholder: 'Enter your password',
  forgotPassword: 'Forgot password?',
  signIn: 'Sign In',
  signingIn: 'Signing in…',
  errorFillFields: 'Please enter your email and password.',
  errorInvalid: 'Invalid email or password.',
  forgotTitle: 'Reset Password',
  forgotSubtitle: 'Enter your email and we will send you reset instructions.',
  submit: 'Send Reset Link',
  cancel: 'Cancel',
  toast: '✅ Reset link sent! Check your inbox.',
};
export const LAYOUT_TEXT = {
  brandAbbr: 'WS',
  brand: 'WorkSync',
  dashboard: 'Dashboard',
  employees: 'Employees',
  attendance: 'Attendance',
  tasks: 'Tasks',
  admin: 'Admin',
  welcomePrefix: 'Hello, ',
  logout: 'Logout',
};
export const DASHBOARD_TEXT = {
  title: 'Dashboard',
  welcome: 'Welcome to WorkSync',
  subtitle: 'Here is an overview of your workforce',
  totalEmployees: 'Total Employees',
  totalTasks: 'Total Tasks',
  attendance: 'Attendance Today',
  recentActivity: 'Recent Activity',
  noActivity: 'No recent activity.',
};
export const TASKS_TEXT = {
  title: 'Tasks',
  subtitle: 'View and manage your assigned tasks',
  noTasks: 'No tasks found',
  noTasksSubtitle: 'You have no tasks assigned yet.',
  status: 'Status',
  priority: 'Priority',
  dueDate: 'Due Date',
  assignedTo: 'Assigned To',
  markComplete: 'Mark Complete',
  loading: 'Loading tasks...',
  errorLoad: 'Failed to load tasks. Please try again.',
  statusUpdated: 'Task status updated.',
  updateFailed: 'Failed to update task status.',
  pagetitle: 'Task Management',
};
